apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend
  namespace: flask-backend  # 追加
spec:
  replicas: 1  # 1 -> 2
  template:
    metadata:
      labels:
        app: flask-backend
    spec:
      serviceAccountName: flask-backend  # Todo: cdkでSAを作成する
      containers:
        - name: flask-backend
          image: 338456725408.dkr.ecr.ap-northeast-1.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_DEFAULT_REGION
              value: ap-northeast-1
            - name: DYNAMODB_TABLE_NAME  # Todo: cdkでDynamoDBを作成する
              value: messages
  selector:
    matchLabels:
      app: flask-backend
